config/routes.rb
Rails.application.routes.draw do
  root 'string_calculator#index'
  post '/calculate', to: 'string_calculator#calculate', as: :calculate
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/string_calculator_controller.rb
# frozen_string_literal: true

# Controller to handle logic for calculator
class StringCalculatorController < ApplicationController
  def index; end

  def calculate
    @numbers = params['numbers']
    @scs = StringCalculatorService.new({ numbers: @numbers })
    @result = @scs.addition
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/string_calculator_helper.rb
module StringCalculatorHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/string_calculator/index.html.erb
<center>
  <%= form_tag(calculate_path) do %>
    <% if @scs.present? %>
      <% @scs.errors.each do |error| %>
        <p><%= error %></p>
      <% end %>
    <% end %>

    <% if @result && @scs.errors.empty? %>
      <p> Output is: <%=  @result %></p>
    <% end %>
    <div>
      <%= label_tag 'numbers', 'Enter a Number:' %>
      <%= text_field_tag :numbers, nil, class: 'form-control', value: @numbers %>
    </div>

    <div>
      <%= submit_tag 'Submit', class: 'btn btn-primary' %>
    </div>
  <% end %>
</center>